name = "iroh-discovery"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

[[kv_namespaces]]
binding = "disco"
id = "ce5dcdc2c4d342eab7d04ce6623c6541"

[build]
command = "cargo install -q worker-build && worker-build --release"
